name: Validate PR

on:
  push:
    # ignore master since the main workflow covers that
    branches-ignore:
      - master
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        tests/test.sh
